=== TalaDiego/2021_LMSGI_DICF/ud4/FormularioContrato.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT datospersonales (nombre,apellido,gmail,contrasenya,DNI,telefono,
          localidad,provincia,fech_nac,direccion,CP,estudios,hamburguesa,
          hora,observaciones)>

<!ATTLIST datospersonales xmlns:xsi CDATA #IMPLIED
xsi:noNamespaceSchemaLocation CDATA #IMPLIED >

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT apellido (#PCDATA)>

<!ELEMENT gmail (#PCDATA)>

<!ELEMENT contrasenya (#PCDATA)>

<!ELEMENT DNI (#PCDATA)>

<!ELEMENT telefono (#PCDATA)>

<!ELEMENT localidad (#PCDATA)>

<!ELEMENT provincia (#PCDATA)>
<!ATTLIST provincia
    provincia (Zamora|Leon|Valladolid|Salamanca|Avila|Soria|Burgos|Palencia|Segovia) #IMPLIED
  >

<!ELEMENT fech_nac (#PCDATA)>

<!ELEMENT direccion (#PCDATA)>

<!ELEMENT CP (#PCDATA)>

<!ELEMENT estudios (si,no)*>

<!ELEMENT si (#PCDATA)>
<!ATTLIST si
    si CDATA #IMPLIED
  >

<!ELEMENT no (#PCDATA)>
<!ATTLIST no
    no CDATA #IMPLIED
  >

<!ELEMENT hamburguesa (pollo,ternera)*>

<!ELEMENT pollo (#PCDATA)>
<!ATTLIST pollo
    tipo CDATA #IMPLIED>

<!ELEMENT ternera (#PCDATA)>
<!ATTLIST ternera
    tipo CDATA #IMPLIED>

<!ELEMENT hora (#PCDATA)>
<!ATTLIST hora
    hora CDATA #IMPLIED
  >

<!ELEMENT observaciones (#PCDATA)>
<!ATTLIST observaciones
    observaciones CDATA #IMPLIED
  >

=== TalaDiego/2021_LMSGI_DICF/ud4/FormularioContrato.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datospersonales SYSTEM 'FormularioContrato.dtd'>
<datospersonales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="FormularioContrato.xsd">
    <nombre>diego</nombre>
    <apellido>casta√±o</apellido>
    <gmail>diego@gmail.com</gmail>
    <contrasenya>paso1234*</contrasenya>
    <DNI>71047190Y</DNI>
    <telefono>607648706</telefono>
    <localidad>Benavente</localidad>
    <provincia></provincia>
    <fech_nac>2002-01-27</fech_nac>
    <direccion>Avenida Luis Moran</direccion>
    <CP>11111</CP>
    <estudios>
        <si>si</si>
        <no>no</no>
    </estudios>
    <hamburguesa>
        <pollo tipo="uno">frito</pollo>
        <ternera tipo="dos">hecha</ternera>
    </hamburguesa>
    <hora>8</hora>
    <observaciones>todo fue bien</observaciones>
</datospersonales>
