=== TalaDiego/2021_LMSGI_DICF/ud4/index.html/mapaestelar.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="mapaestelar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="constelacion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombreespaÃ±ol" type="xs:string"/>
                            <xs:element name="superficie" type="xs:float"/>
                            <xs:element name="estrellas">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:positiveInteger">
                                            <xs:element name="asterismo"/>
                                        </xs:extension>
                                        <xs:extension base="xs:float">
                                            <xs:element name="masBrillante"/>
                                        </xs:extension> 
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="objetos">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:boolean">
                                            <xs:element name="cumulos"/>
                                        </xs:extension>
                                        <xs:extension base="xs:boolean">
                                            <xs:element name="nebulosas"/>
                                        </xs:extension>
                                        <xs:extension base="xs:boolean">
                                            <xs:element name="galaxias"/>
                                        </xs:extension>
                                        <xs:extension base="xs:boolean">
                                            <xs:element name="cuasares"/>
                                        </xs:extension>
                                        <xs:extension base="xs:boolean">
                                            <xs:element name="lluviademeteoros"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="colindantes" type="xs:string"/>
                            <xs:element name="observacion">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:element name="hemisferio"/>
                                        </xs:extension>
                                        <xs:extension base="xs:integer">
                                            <xs:element name="mes"/>
                                        </xs:extension>
                                        <xs:extension base="xs:time">
                                            <xs:element name="hora"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TalaDiego/2021_LMSGI_DICF/ud4/index.html/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>

<mapaestelar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="mapaestelar.xsd">
    <constelacion nombreLatin="Ursa Maior">
        <nombreespañol>La Osa Mayor</nombreespañol>
        <superficie>1279.7</superficie>
        <estrellas numerodeestrellas="209">
            <asterismo>7</asterismo>
            <masBrillante luminosidad="1.77">Alioth</masBrillante>
        </estrellas>
        <objetos>
            <cumulos>false</cumulos>
            <nebulosas>true</nebulosas>
            <galaxias>true</galaxias>
            <cuasares>false</cuasares>
            <lluviademeteoros></lluviademeteoros>
        </objetos>
        <colindantes></colindantes>
        <observacion>
            <hemisferio></hemisferio>
            <mes></mes>
            <hora></hora>
        </observacion>
    </constelacion>
</mapaestelar>
